runtime: nodejs18
env: standard

handlers:
  - url: /static
    static_dir: build/static
  - url: /(.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg)$
  - url: /.*
    static_files: build/index.html
    upload: build/index.html 